import CustomNavbar from "@/components/CustomNavbar";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";
import UserContext from "@/context/userContext";
import UserProvider from "@/context/userProvider";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      
        <UserProvider>
          <CustomNavbar  />
          <div className="mt-0">{children}</div>

          <Footer />
          <Toaster position='top-right'/>
        </UserProvider>
      </body>
    </html>
  );
}
